---
title: "Remote Sensing in the Social Sciences"
date: "Fall 2022 | AAEC 6984 | Prof Benami"
site: bookdown::bookdown_site
always_allow_html: true
output:
  html_document:
    toc: true
  bookdown::pdf_document2:
    latex_engine: xelatex
    toc: true
---

```{r setup_prelab, include=FALSE}
htmltools::tagList(rmarkdown::html_dependency_font_awesome())
file.create('.nojekyll')
# bookdown::clean_book(TRUE)
# bookdown::clean_book(clean = getOption("bookdown.clean_book", TRUE))
```

# Introduction {-}

## Why Google Earth Engine? 

Research in Remote Sensing has evolved drastically over the past few decades. 

In the earliest years of remote sensing analysis, only a handful of governments had the capability to deploy satellites and reliably process the imagery, while the use was largely limited to the military and intelligence communities. In the late 1950s, the US and Europe established the National Aeronautics and Space Administration (NASA) and the origins of the European Space Agency (ESA) to support a civilian space program as well as space and aeronautics research. Even then, data access was unwieldy and costly - if a researcher had identified the data they needed, they would have to go through the highly complicated and time-intensive steps of downloading the data onto a mainframe computer with sufficient storage and processing capability t performing a series of pre-processing steps (e.g. orthorectification and atmospheric corrections), all before they could start analysis. 

**Enter Google Earth Engine (GEE).** As part of Google's quest to make the world's information universally accessible and useful, Google Earth Engine emerged in 2010 to aid in organizing and simplifying geospatial data in a way that supports an end-to-end solution. This is a valuable tool simplifies many of the historical problems that Remote Sensing researchers have struggled with. Google has collected and maintains petabytes of imagery from both public and private sources, including the most-used Landsat, MODIS, and Sentinel data. Additionally, GEE allows users to process the data and conduct sophisticated analysis within Google's Cloud environment (even allowing advanced Machine Learning using TensorFlow Processing Units). They geo-rectify the imagery and provide pre-built algorithms that facilitate analysis. In case you need to build your own algorithms, Google Earth Engine has  functionality within JavaScript and Python, which in turn extends the opportunities for processing data and displaying results. The user can even import their own data and work with it within GEE. Finally, the user owns the analysis and algorithms written within GEE, providing fair and open use.   

As researchers  involved in Remote Sensing, Google Earth Engine provides an invaluable toolset that you can use throughout your career. 

## License and Attribution

This work is licensed under a[ Creative Commons Attribution 4.0 International License](http://creativecommons.org/licenses/by/4.0/). The foundation of these lab exercises were generously shared with us by Nicholas Clinton (Google) and Dr. David Saah (University of San Francisco, Geospatial Analysis Lab). We thank them for this great public good and take responsibility for any errors that arose from our adaptation.

Elinor Ben-Ami and [Ozzy Campos](https://www.linkedin.com/in/adam-ozzy-c-553b37a9/) have extended and customized these labs and exercise and incorporated them into the course 'Remote Sensing for Social Science'.  
